global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: quickstart-github-enterprise
  s3bucket: tonynv
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - ca-central-1
    - eu-west-1
    - eu-west-2
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  github:
    parameter_input: quickstart-github-enterprise-taskcat.json
    template_file: quickstart-github-enterprise-master.template
